# Generated by Django 4.2 on 2025-11-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
